version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.2
  shellcheck: circleci/shellcheck@3.2

# Filter definitions
filters: &dev_filters
  tags:
    ignore: /.*/
  branches:
    only: staging

prod_filters: &prod_filters
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
  branches:
    ignore: /.*/  # Don't trigger on any branch, only on tags

# Common job requirements
common_requires: &common_requires
  [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]

workflows:
  # Dev/Staging workflow
  lint-pack-dev:
    triggers:
      - schedule:
          cron: "0 0 * * *"  # Run at midnight UTC every day
          filters:
            branches:
              only: staging
    jobs:
      - orb-tools/lint:
          filters: *dev_filters
      - orb-tools/pack:
          filters: *dev_filters
      - orb-tools/review:
          filters: *dev_filters
      - shellcheck/check:
          filters: *dev_filters
      - orb-tools/publish:
          orb_name: bluetel/aws-ecs
          vcs_type: << pipeline.project.type >>
          pub_type: dev
          context: orb-publisher
          requires: *common_requires
          filters: *dev_filters

  # Production workflow - tag based
  publish-prod:
    jobs:
      - orb-tools/lint:
          filters: *prod_filters
      - orb-tools/pack:
          filters: *prod_filters
      - orb-tools/review:
          filters: *prod_filters
      - shellcheck/check:
          filters: *prod_filters
      - orb-tools/publish:
          orb_name: bluetel/aws-ecs
          vcs_type: << pipeline.project.type >>
          pub_type: production
          context: orb-publisher
          requires: *common_requires
          filters: *prod_filters